apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote-back
spec:
  template:
    spec:
      containers:
      - name: azure-vote-back
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi