apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ubuntu-iptables
  name: ubuntu-iptables
spec:
  containers:
    - image: ubuntu
      name: ubuntu-iptables
      command:
        - sleep
        - "36000"
      securityContext:
        capabilities:
          add:
            - CAP_NET_ADMIN
            - CAP_NET_RAW
