apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: cuser-request
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1pqQ0NBVTRDQVFBd0lURU9NQXdHQTFVRUF3d0ZZM1Z6WlhJeER6QU5CZ05WQkFvTUJtTm5jbTkxY0RDQwpBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQUtWY1U4NHZQT0FXWXI1RVhkdGJEZjlUCjh2WDhLZS9xaTR2eWlWaTRWOVd3bDF5TEhDYWsrdDFxMTFhMUd4OGZpUmNOSEtPbkZTOHE0dGJyNDdWSUNEaUgKc0VQb1dUdkJBbk1RR3V2MTBMbTJCemhPRDl2cXRGS3NGaE44RDNDSmQwMW9HN3dHN1dLcnVoaVVkV1hBUzdZUwpkdC8reko5MGdxa01KSTRGVkg4OEdneGd2MDRKYmVEaE5jZWtubXZlbXBHWTgxUmJKNENtbUE1N1ZPMUVqVFpJCkt3WDNjTTRnSFFYL3RlQVpzVGdJVWRadkl5Z3JWNFN0T2I4SnhSZ1RPaVlTcC9CRXZlWFhXbHhpMUczS2V6YXgKZSswK0lncVpTMy93RE93YW5IN1IzN2lLWEorQUJRQ2FsdStDZFJFVVBEdHd3dis2eFJLaE5HeGd6MDNZdnc4QwpBd0VBQWFBQU1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ0F1blRaRGtheW52V1dSTHBMaTJPcEIwaWZpTnZzCnFFSW03TXdWN1E4V1RvY2RWN0dmU3VTV3lqaFV5dVZMb0FGN2xyV01DQlY2Mk1wcTZpWHZDZGlBY05GM0xkajAKYkhNN0RZVjZJV20rR2xqazhwL3AwZUpYcDJYVDN0ME1KeGtnSUdJVlVwOERuenQ4c2FjZUtZY3BuTGU2M2VEQQpETnJ0Z241RjNRcUpZYmpsdTIxTXZKVEErK080a05tNktkVWFEQXMxTjY5VzFEOVc2S1VqRlQyaXpxWUhhUVVZCnYveEZsekdmM0RDTUg3Q3VBcFlvVFZKQXR6QkZGYkhhNWlIQ05vaERmcDc4bFZVZktvcGVEc0JjNm4wQzUwOFkKdkcrMldJd2Q2cDgvc3ByQ2Y5Yko0VitROVZ2YWRpZEtLdUVNMFJmTUZ1dHBrN1p2MERCdVpFMmwKLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 7776000
  usages:
  - digital signature
  - key encipherment
  - client auth
