apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: demo-restricted
    pod-security.kubernetes.io/enforce-version: v1.29
    pod-security.kubernetes.io/enforce: restricted
  name: demo-restricted
