apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cuser-pods
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-user
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: cuser
