apiVersion: v1
data:
  config.json: ewogICJ1cmwiOiAiaHR0cHM6Ly9leGFtcGxlLmNvbS9ScmFXaXJRMTFBdGdXaGJHdnpmMDhfMndWRkRyZ2JPNHJZR1NvVjR2Q3U4IiwKICAic2VjcmV0IjogIkdSNlBibldwVmxUQXRrM0tBOHYyR3JYM28yRFg4clQteGl3RzVBVmw2NDYzT19adHRYSElLekZIQ0JUNEkwUGNTZXZQVkZQTzRadWVkRVJYZDNfTkhnIgp9Cg==
kind: Secret
metadata:
  name: config
