apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: demoapp
  name: demoapp
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 31234
  type: NodePort
  selector:
    app.kubernetes.io/name: demoapp
